In [1]:
import os
import random
import numpy as np
import matplotlib.pyplot as plt
from collections import deque
from enum import Enum, IntEnum

## **Without toroidal wrapping**

In [2]:
class Move_State(IntEnum):
    VALID = 1
    INVALID = 0

In [24]:
array_1d = np.arange(20)
array_1d = np.delete(array_1d, [4,5])
print(array_1d)

[ 0  1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
array_1d = np.arange(20)
n_rows = 4
n_cols = 5
aux_matrix = array_1d.reshape(n_rows, n_cols)
print(aux_matrix)

index_to_select = 8
print(f"Index selected: {index_to_select}")

cell_row = index_to_select // n_cols
cell_col = index_to_select % n_cols
above_idx = (cell_row - 1) * n_cols + cell_col
below_idx = (cell_row + 1) * n_cols + cell_col
left_idx = cell_row * n_cols + (cell_col - 1)
right_idx = cell_row * n_cols + (cell_col + 1)

neighbor_indices = [above_idx, below_idx, left_idx, right_idx]
print("Neighbor indices:", neighbor_indices)

for i, idx in enumerate(neighbor_indices.copy()):
    # Check if index is within valid range
    if idx < 0 or idx >= array_1d.size:
        neighbor_indices.remove(idx)
        continue

    # For horizontal neighbors, ensure they remain in the same row as 'index_to_select'
    neighbor_row = idx // n_cols
    if abs(idx - index_to_select) == 1 and neighbor_row != cell_row:
        neighbor_indices.remove(idx)

print("Valid neighbor indices:", neighbor_indices)
print("Max cell value:", np.max(array_1d[neighbor_indices]))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Index selected: 8
Neighbor indices: [3, 13, 7, 9]
Valid neighbor indices: [3, 13, 7, 9]
Max cell value: 13


---
---
---

In [ ]:
epsilon_max = 1.0
epsilon_min = 0.01
epsilon_history = []
episodes = 100
for i in range(episodes):
    # Use episodes-1 in the denominator to ensure epsilon_min is reached at the final episode
    epsilon = epsilon_min + 0.5 * (epsilon_max - epsilon_min) * (1 + np.cos(np.pi * i / (episodes - 1)))
    epsilon_history.append(epsilon)

def plot_epsilon_history(epsilon_history: list, file_name: str) -> None:
    """
    Plot the epsilon history during the training process.
    """
    plt.figure(figsize=(12, 6))
    plt.plot(epsilon_history, label='Epsilon')
    plt.xlabel('Episodes')
    plt.ylabel('Epsilon')
    plt.title('Epsilon vs Episodes')
    plt.legend()
    plt.savefig(file_name) # always in folder results
    plt.close()

plot_epsilon_history(epsilon_history, 'results/V3_version/epsilon_history.png')

In [25]:
q_table = np.loadtxt('results/V3_version/V3_1_Qtable_585_100.txt')

print(f"Total number of values in q_table: {q_table.size}")

num_zeros = np.count_nonzero(q_table == 0)
print(f"Number of zeros in q_table: {num_zeros}")

num_neg_ones = np.count_nonzero(q_table == -1)
print(f"Number of -1 in q_table: {num_neg_ones}")

percentage_zeros = (num_zeros / q_table.size) * 100
print(f"Percentage of zeros in q_table: {percentage_zeros:.2f}%")
print("*"*50)

# Get unique values and their counts
unique_values, counts = np.unique(q_table, return_counts=True)

# Create a list of tuples (value, count) and sort it by count in descending order
value_counts = sorted(zip(unique_values, counts), key=lambda x: x[1], reverse=True)

# Get the top 10 most repeated values and their counts
top_10_values = value_counts[:10]

print("Top 10 most repeated values and their counts:")
for value, count in top_10_values:
    print(f"Value: {value}, Count: {count}")

# Calculate the sum of counts of the top 10 most repeated values
sum_top_10_counts = sum(count for _, count in top_10_values)
print(f"Sum of counts of the top 10 most repeated values: {sum_top_10_counts}")
print("*"*50)

num_positive_values = np.count_nonzero(q_table > 0)
print(f"Number of positive values in q_table: {num_positive_values}")

# Get unique positive values and their counts
unique_values, counts = np.unique(q_table[q_table > 0], return_counts=True)

# Create a list of tuples (value, count) and sort it by count in descending order
value_counts = sorted(zip(unique_values, counts), key=lambda x: x[1], reverse=True)

# Get the top 10 most repeated positive values and their counts
top_10_positive_values = value_counts[:10]

print("Top 10 most repeated positive values and their counts")
for value, count in sorted(top_10_positive_values, reverse=True):
    print(f"Value: {value}, Count: {count}")

Total number of values in q_table: 342225
Number of zeros in q_table: 291003
Number of -1 in q_table: 0
Percentage of zeros in q_table: 85.03%
**************************************************
Top 10 most repeated values and their counts:
Value: 0.0, Count: 291003
Value: nan, Count: 48863
Value: -0.01, Count: 1583
Value: -inf, Count: 523
Value: 0.15, Count: 253
Sum of counts of the top 10 most repeated values: 342225
**************************************************
Number of positive values in q_table: 253
Top 10 most repeated positive values and their counts
Value: 0.15, Count: 253


In [2]:
# Read lists from a txt file
with open('../../results/data.txt', 'r') as f:
    lines = f.readlines()
    rewards = eval(lines[0].split(': ')[1])
    max_rewards = eval(lines[1].split(': ')[1])
    actions_done = eval(lines[2].split(': ')[1])
    min_actions_done = eval(lines[3].split(': ')[1])
    areas_scratched = eval(lines[4].split(': ')[1])
    min_areas_scratched = eval(lines[5].split(': ')[1])

# # Save lists to a txt file
# with open('results/data.txt', 'w') as f:
#     f.write(f"rewards: {rewards}\n")
#     f.write(f"max_rewards: {max_rewards}\n")
#     f.write(f"actions_done: {actions_done}\n")
#     f.write(f"min_actions_done: {min_actions_done}\n")
#     f.write(f"areas_scratched: {areas_scratched}\n")
#     f.write(f"min_areas_scratched: {min_areas_scratched}\n")